language: python
python:
- 3.8

before_install:
 - pip install coverage
 - pip install ez_setup
install:
 - pip install ".[test]" .
script:
 - coverage run -m unittest discover
after_success:
 - bash <(curl -s https://codecov.io/bash)
